name: e2e:tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  e2e_client:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Enable Yarn
        run: corepack enable yarn

      - name: Install project dependencies
        run: yarn install

      - name: Playwright install
        run: yarn playwright install --with-deps chromium

      - name: Run Playwright tests
        run: yarn playwright test
#        env:
#          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
